### ISSUE TITLE
[query] Fuse Block implementation

### ISSUE THREAD

**Issue by akikinho** [wireviz/WireViz#402] opened 2024-07-09 13:04 UTC
Hello Wireviz team,
Is there a way to show a fuse block? Can it be shown using connectors?

Thank you and Best Regards

**Comment by kvid** [comment] 2024-07-09 15:27
Is this issue and #397 example use cases of your #389 generic request? In that case, the latter probably is a duplicate of #142.

A two-pin connector with "fuse" or "⏛" as type might be something you can try out within the current functionality.

Please also prioritize to follow up our questions in your issues #399 and #389

**Comment by akikinho** [comment] 2024-07-09 15:33
Thank you @kvid. I have implemented your suggestion.

**Closed** 2024-07-10 22:59 UTC
